[debug] [2024-02-02T12:25:23.768Z] ----------------------------------------------------------------------
[debug] [2024-02-02T12:25:23.771Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Maxi\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-02-02T12:25:23.771Z] CLI Version:   13.1.0
[debug] [2024-02-02T12:25:23.771Z] Platform:      win32
[debug] [2024-02-02T12:25:23.771Z] Node Version:  v20.10.0
[debug] [2024-02-02T12:25:23.772Z] Time:          Fri Feb 02 2024 09:25:23 GMT-0300 (hora estándar de Argentina)
[debug] [2024-02-02T12:25:23.772Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-02-02T12:25:23.775Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[debug] [2024-02-02T12:25:24.262Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2024-02-02T12:25:24.263Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=461613078&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-02-02T12:25:38.128Z] Error: spawn cmd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-02-02T12:25:49.623Z] ----------------------------------------------------------------------
[debug] [2024-02-02T12:25:49.627Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Maxi\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-02-02T12:25:49.627Z] CLI Version:   13.1.0
[debug] [2024-02-02T12:25:49.628Z] Platform:      win32
[debug] [2024-02-02T12:25:49.628Z] Node Version:  v20.10.0
[debug] [2024-02-02T12:25:49.628Z] Time:          Fri Feb 02 2024 09:25:49 GMT-0300 (hora estándar de Argentina)
[debug] [2024-02-02T12:25:49.628Z] ----------------------------------------------------------------------
[debug] 
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=361190974&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-02-02T12:25:51.899Z] Error: spawn cmd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.
